<a href="https://colab.research.google.com/github/Nishmitha2721/20221COM0111/blob/main/labsheet4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
meteorites=pd.read_csv('/Meteorite_Landings (1) (1).csv',nrows=5)
meteorites

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [ ]:
meteorites.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

In [ ]:
import requests

response = requests.get(
    'https://data.nasa.gov/resource/gh4g-9sfh.json',
    params={'$limit': 50_000}
)

if response.ok:
  payload = response.json()
else:
  print(f'Request was not successful and returned code : {response.status_code}')
  payload = None

In [ ]:
meteorites.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
import pandas as pd

df=pd.DataFrame(payload)
df.head(3)

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,geolocation,:@computed_region_cbhk_fwbd,:@computed_region_nnqa_25f4
0,Aachen,1,Valid,L5,21,Fell,1880-01-01T00:00:00.000,50.775000,6.083330,"{'latitude': '50.775', 'longitude': '6.08333'}",NaN,NaN
1,Aarhus,2,Valid,H6,720,Fell,1951-01-01T00:00:00.000,56.183330,10.233330,"{'latitude': '56.18333', 'longitude': '10.23333'}",NaN,NaN
2,Abee,6,Valid,EH4,107000,Fell,1952-01-01T00:00:00.000,54.216670,-113.000000,"{'latitude': '54.21667', 'longitude': '-113.0'}",NaN,NaN

In [ ]:
meteorites.shape

(5, 10)

In [ ]:
meteorites.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

In [ ]:
meteorites.dtypes

name            object
id               int64
nametype        object
recclass        object
mass (g)         int64
fall            object
year            object
reclat         float64
reclong        float64
GeoLocation     object
dtype: object

In [ ]:
meteorites.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [ ]:
meteorites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         5 non-null      object
 1   id           5 non-null      int64
 2   nametype     5 non-null      object
 3   recclass     5 non-null      object
 4   mass (g)     5 non-null      int64
 5   fall         5 non-null      object
 6   year         5 non-null      object
 7   reclat       5 non-null      float64
 8   reclong      5 non-null      float64
 9   GeoLocation  5 non-null      object
dtypes: float64(2), int64(2), object(6)
memory usage: 528.0+ bytes

In [ ]:
meteorites.name

0      Aachen
1      Aarhus
2        Abee
3    Acapulco
4     Achiras
Name: name, dtype: object

In [ ]:
meteorites[['name','mass (g)']]

       name  mass (g)
0    Aachen        21
1    Aarhus       720
2      Abee    107000
3  Acapulco      1914
4   Achiras       780

In [ ]:
meteorites[100:104]

Empty DataFrame
Columns: [name, id, nametype, recclass, mass (g), fall, year, reclat, reclong, GeoLocation]
Index: []

In [ ]:
meteorites.iloc[100:104,[0,3,4,6]]

Empty DataFrame
Columns: [name, recclass, mass (g), year]
Index: []

In [ ]:
meteorites.loc[100:104, 'mass (g)':'year']

Empty DataFrame
Columns: [mass (g), fall, year]
Index: []

In [ ]:
(meteorites['mass (g)'] > 50) & (meteorites.fall =='Found')

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
meteorites[(meteorites['mass (g)']> 1e6) &(meteorites.fall =='Fell')]

Empty DataFrame
Columns: [name, id, nametype, recclass, mass (g), fall, year, reclat, reclong, GeoLocation]
Index: []

In [ ]:
meteorites.fall.value_counts()

Fell    5
Name: fall, dtype: int64

In [ ]:
meteorites.query

<bound method DataFrame.query of        name   id nametype     recclass  mass (g)  fall  \
0    Aachen    1    Valid           L5        21  Fell
1    Aarhus    2    Valid           H6       720  Fell
2      Abee    6    Valid          EH4    107000  Fell
3  Acapulco   10    Valid  Acapulcoite      1914  Fell
4   Achiras  370    Valid           L6       780  Fell

                     year    reclat    reclong           GeoLocation
0  01/01/1880 12:00:00 AM  50.77500    6.08333     (50.775, 6.08333)
1  01/01/1951 12:00:00 AM  56.18333   10.23333  (56.18333, 10.23333)
2  01/01/1952 12:00:00 AM  54.21667 -113.00000    (54.21667, -113.0)
3  01/01/1976 12:00:00 AM  16.88333  -99.90000     (16.88333, -99.9)
4  01/01/1902 12:00:00 AM -33.16667  -64.95000   (-33.16667, -64.95)  >

In [ ]:
meteorites.fall.value_counts(normalize=True)

Fell    1.0
Name: fall, dtype: float64

In [ ]:
meteorites['mass (g)'].mean()

22087.0

In [ ]:
meteorites['mass (g)'].quantile([0.01,0.05,0.5,0.95,0.99])

0.01        48.96
0.05       160.80
0.50       780.00
0.95     85982.80
0.99    102796.56
Name: mass (g), dtype: float64

In [ ]:
meteorites['mass (g)'].median()

780.0

In [ ]:
meteorites['mass (g)'].max()

107000

In [ ]:
meteorites.loc[meteorites['mass (g)'].idxmax()]

name                             Abee
id                                  6
nametype                        Valid
recclass                          EH4
mass (g)                       107000
fall                             Fell
year           01/01/1952 12:00:00 AM
reclat                       54.21667
reclong                        -113.0
GeoLocation        (54.21667, -113.0)
Name: 2, dtype: object

In [ ]:
meteorites.recclass.nunique()

5

In [ ]:
meteorites.recclass.unique()[:14]

array(['L5', 'H6', 'EH4', 'Acapulcoite', 'L6'], dtype=object)

In [ ]:
meteorites.describe(include='all')

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
count,5,5.000000,5,5,5.000000,5,5,5.000000,5.000000,5
unique,5,NaN,1,5,NaN,1,5,NaN,NaN,5
top,Aachen,NaN,Valid,L5,NaN,Fell,01/01/1880 12:00:00 AM,NaN,NaN,"(50.775, 6.08333)"
freq,1,NaN,5,1,NaN,5,1,NaN,NaN,1
mean,NaN,77.800000,NaN,NaN,22087.000000,NaN,NaN,28.978332,-52.306668,NaN
std,NaN,163.383598,NaN,NaN,47472.657372,NaN,NaN,38.276856,57.942434,NaN
min,NaN,1.000000,NaN,NaN,21.000000,NaN,NaN,-33.166670,-113.000000,NaN
25%,NaN,2.000000,NaN,NaN,720.000000,NaN,NaN,16.883330,-99.900000,NaN
50%,NaN,6.000000,NaN,NaN,780.000000,NaN,NaN,50.775000,-64.950000,NaN
75%,NaN,10.000000,NaN,NaN,1914.000000,NaN,NaN,54.216670,6.083330,NaN
max,NaN,370.000000,NaN,NaN,107000.000000,NaN,NaN,56.183330,10.233330,NaN